controller:
  admin:
    username: admin
    password: admin

  serviceType: NodePort
  service:
    port: 8080
    nodePort: 32524

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

persistence:
  enabled: false
