apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: application
      version: blue
  template:
    metadata:
      labels:
        app: application
        version: blue
    spec:
      containers:
      - name: application
        image: "{{ .Values.image.repository }}:{{ .Values.image.blueTag }}"
        ports:
        - containerPort: 8080